name: Run Playwright Tests

# Trigger the workflow manually and also on push to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      # Run Playwright tests and generate reports
      - name: Run Playwright tests
        run: npx playwright test
        env:
          URL: ${{ secrets.URL }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}

      # Upload JUnit test report to GitHub
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-report
          path: test-results/results.xml

      # Publish JUnit Test Results to GitHub UI
      - name: Publish JUnit Test Results
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/test-results/results.xml'
          check_name: 'Playwright Test Results'
          require_tests: true
          fail_on_failure: false
