name: Run Playwright Tests

# Trigger the workflow manually and also on push to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      # Create the .env file from GitHub secrets
      - name: Create .env file
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> ./config/.env
          echo "USERNAME=${{ secrets.USERNAME }}" >> ./config/.env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> ./config/.env
          echo "COMMON_TIMEOUT=${{ secrets.COMMON_TIMEOUT }}" >> ./config/.env

      # Run Playwright tests
      - name: Run Playwright tests
        run: npm run prod
        env:
          ENV: prod

      # Upload the Playwright HTML report
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
