name: Run Playwright Tests

# Trigger the workflow manually and also on push to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      # Run Playwright tests and generate reports
      - name: Run Playwright tests
        run: npm run test
        env:
          URL: ${{ secrets.URL }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}

      # Publish JUnit Test Report to GitHub Actions UI
      - name: Publish JUnit Test Report
        uses: dorny/test-reporter@v1
        if: always()  # Run this step even if tests fail
        with:
          name: Playwright Tests
          path: test-results/results.xml
          reporter: junit
          fail-on-error: false
